#!/usr/bin/env python

from pandocfilters import toJSONFilter, Para, BulletList

def deflists(key, value, format, meta):
    if key == 'DefinitionList':
        return BulletList([[b for d in defs for b in d] for [t, defs] in value])

if __name__ == "__main__":
    toJSONFilter(deflists)
